# Load distro-specific variables
- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- block:
  - import_tasks: software/google-chrome.yml
  - import_tasks: software/code.yml
  - import_tasks: software/nvm.yml
