# Load distro-specific variables
- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- block:

  - include_tasks: desktop_environments/i3/config.yml
    when: i3 is defined and i3 == true

  - import_tasks: software/google-chrome.yml
  - import_tasks: software/code.yml
  - import_tasks: software/tex.yml
  - import_tasks: software/nvm.yml
