# Load distro-specific variables
- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- block:

  - include_tasks:
      - desktop_environments/i3/config.yml
      - desktop_environments/i3/pulseaudio.yml
    when: i3 is defined and i3 == true

  - import_tasks: software/fonts.yml
  - import_tasks: software/google-chrome.yml
  - import_tasks: software/firefox.yml
  - import_tasks: software/syncthing.yml
  - import_tasks: software/bitwarden.yml
  - import_tasks: software/joplin.yml
  - import_tasks: software/libreoffice.yml
  - import_tasks: software/zathura.yml
  - import_tasks: software/mpv.yml
  - import_tasks: software/flameshot.yml
  - import_tasks: software/discord.yml
  - import_tasks: software/caprine.yml
  - import_tasks: software/spotify.yml
  - import_tasks: software/code.yml
  - import_tasks: software/tex.yml
  - import_tasks: software/nvm.yml
