- name: yum code repo installation
  tags:
    - code
  when: ansible_distribution == "Fedora"
  block:
    - name: code | install rpm key  
      ansible.builtin.rpm_key:
        key: https://packages.microsoft.com/keys/microsoft.asc

    - name: code | copy yum repo
      ansible.builtin.copy:
        src: code/yum_vscode.repo
        dest: /etc/yum.repos.d/vscode.repo
        owner: root
        group: root
        mode: u=rw,g=r,o=r

- name: code | install
  tags:
    - code
  package:
    name:
      - code

- name: code | marketplace
  tags:
    - code
  aur:
    name:
      - code-marketplace
  become: yes
  become_user: aur_builder
  when: ansible_distribution == "Archlinux"
