- name: install code
  tags:
    - code
  package:
    name:
      - code
  when: ansible_distribution == "Archlinux"

- name: install code-marketplace
  tags:
    - code
  aur:
    name:
      - code-marketplace
  become: yes
  become_user: aur_builder
  when: ansible_distribution == "Archlinux"
