- name: flameshot
  tags:
    - screenshot
    - flameshot
  block:
    - name: flameshot | install
      package:
        name:
          - flameshot
    - name: flameshot | create config directory
      file:
        path: /home/{{ user_name }}/.config/flameshot
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        mode: "u=rwx,go=rx"
        state: directory
    
    - name: flameshot | copy config
      copy:
        src: flameshot/flameshot.ini
        dest: /home/{{ user_name }}/.config/flameshot/flameshot.ini
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        mode: "u=rw,go=r"
        backup: yes
