- name: google-chrome | aur install
  tags:
    - browser
    - chrome
  aur:
    name:
      - google-chrome
  become: yes
  become_user: aur_builder
  when: ansible_distribution == "Archlinux"

- name: google-chrome | set default browser mimeapps
  tags:
    - browser
    - chrome
  replace:
    path: /home/{{user_name}}/.config/mimeapps.list
    regexp: 'userapp-Pale Moon'
    replace: 'google-chrome'

- name: google-chrome | set default browser bashrc
  lineinfile:
    path: "{{ item }}"
    line: BROWSER=/usr/bin/google-chrome-stable
  with_items: ["/home/{{user_name}}/.bashrc", "/home/{{user_name}}/.zshrc" ]
