- name: google-chrome | aur install
  tags:
    - browser
    - chrome
  aur:
    name:
      - google-chrome
  become: yes
  become_user: aur_builder
  when: ansible_distribution == "Archlinux"

- name: google-chrome | set default browser mimeapps
  tags:
    - browser
    - chrome
  replace:
    path: /home/{{ user_name }}/.config/mimeapps.list
    regexp: 'userapp-Pale Moon'
    replace: 'google-chrome'

- name: google-chrome | set default browser profile
  tags:
    - browser
    - chrome
  replace:
    path: /home/{{ user_name }}/.profile
    regexp: '/usr/bin/palemoon'
    replace: '/usr/bin/google-chrome-stable'
