- name: node version manager
  tags:
    - node
    - nvm
  when: ansible_distribution == "Archlinux"
  block:
    - name: nvm | install node version manager
      ansible.builtin.package:
        name:
          - nvm
    
    - name: nvm | add to shell
      ansible.builtin.lineinfile:
        path: "{{ item }}"
        line: source /usr/share/nvm/init-nvm.sh
      loop:
        - '/home/{{ user_name }}/.bashrc'
        - '/home/{{ user_name }}/.zshrc'
