- name: syncthing | dnf repo
  ansible.builtin.shell: dnf config-manager --add-repo https://download.opensuse.org/repositories/home:mkittler/Fedora_34/home:mkittler.repo
  when: ansible_distribution == "Fedora"

- name: syncthing | dnf install
  ansible.builtin.package:
    name:
      - syncthingtray
  when: ansible_distribution == "Fedora"

- name: install syncthingtray aur
  tags:
    - browser
    - chrome
  kewlfft.aur.aur:
    name:
      - syncthingtray
  become: yes
  become_user: aur_builder
  when: ansible_distribution == "Archlinux"
