- name: neovim
  tags:
    - vim
    - neovim
    - editor
  block:
    - name: neovim | install neovim
      package:
        name:
          - neovim

    - name: neovim | set default editor to neovim
      blockinfile:
        path: "{{ item }}"
        marker: "# {mark} ANSIBLE MANAGED BLOCK - neovim"
        block: |
          export VISUAL=nvim
          export EDITOR="$VISUAL"
      loop:
        - /home/{{ user_name }}/.bashrc
        - /home/{{ user_name }}/.zshrc
