- name: neovim
  tags:
    - vim
    - neovim
    - editor
  block:
    - name: neovim | install neovim
      package:
        name:
          - neovim

    - name: neovim | set default editor to neovim
      blockinfile:
        path: "{{ item }}"
        marker: "# {mark} ANSIBLE MANAGED BLOCK - neovim"
        block: |
          export VISUAL=nvim
          export EDITOR="$VISUAL"
      loop:
        - /home/{{ user_name }}/.bashrc
        - /home/{{ user_name }}/.zshrc

    - name: neovim | create plugin directory
      file:
        path: /home/{{ user_name}}/.local/share/nvim/site/autoload
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        mode: "u=rwx,go=rx"
        state: directory

    - name: neovim | get vim-plug
      uri:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: /home/{{ user_name }}/.local/share/nvim/site/autoload/plug.vim
        creates: /home/{{ user_name }}/.local/share/nvim/site/autoload/plug.vim
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        mode: "u=rw,go=r"
        
    - name: neovim | create config directory
      file:
        path: /home/{{ user_name}}/.config/nvim
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        mode: "u=rwx,go=rx"
        state: directory

    - name: neovim | copy config
      copy:
        src: neovim/init.vim
        dest: /home/{{ user_name }}/.config/nvim/init.vim
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        mode: "u=rw,go=r"
        backup: yes

