- name: neovim
  tags:
    - vim
    - neovim
    - editor
  block:
    - name: neovim | install neovim
      package:
        name:
          - neovim

    - name: neovim | set default editor to neovim
      lineinfile:
        path: "{{ item }}"
        line: $EDITOR=nvim
        loop:
          - /home/{{ user_name }}/.bashrc
          - /home/{{ user_name }}/.zshrc
