- name: python3
  tags:
    - python
    - pip
  block:
    - name: python3 | install python3 and modules
      package:
        name:
          - "{{ python_package }}"
          - "{{ python_pip_package }}"
          - "{{ python_virtualenv_package }}"

    - name: python3 | install pip packages
      become_user: owen
      pip:
        executable: /usr/bin/pip3
        state: latest
        name:
          - pipx

    - name: python3 | pipx bashrc
      lineinfile:
        path: /home/owen/.bashrc
        line: eval "$(register-python-argcomplete pipx)"

    - name: python3 | pipx zsh
      blockinfile:
        path: /home/owen/.zshrc
        marker: "# {mark} ANSIBLE MANAGED BLOCK - pipx"
        block: |
          autoload -U bashcompinit
          bashcompinit
          eval "$(register-python-argcomplete pipx)"




