- name: ranger
  tags:
    - ranger
    - terminal
    - file-manager
  block:
    - name: ranger | install ranger file manager
      package:
        name:
          - ranger

    - name: ranger | add ranger cd shortcut to .bashrc and .zshrc
      blockinfile:
        path: "{{ item }}"
        marker: "# {mark} ANSIBLE MANAGED BLOCK - ranger"
        block: |
          function ranger-cd {
            tempfile="$(mktemp -t tmp.XXXXXX)"
            ranger --choosedir="$tempfile" "${@:-$(pwd)}"
            test -f "$tempfile" &&
            if [ "$(cat -- "$tempfile")" != "$(echo -n `pwd`)" ]; then
              cd -- "$(cat "$tempfile")"
            fi
            rm -f -- "$tempfile"
          }
          if [ -t 1 ];
          then
            bind '"\C-o":"ranger-cd\C-m"'
          fi
      loop: ["/home/{{ user_name }}/.bashrc", "/home/{{ user_name }}/.zshrc"]