- name: terminal
  tags:
    - terminal
    - zsh
    - bash
  block:
    - name: terminal | install main termial applications
      package:
        name:
          - tmux
          - zsh


    - name: terminal | check for ohmyzsh
      stat:
        path: /home/{{ user_name }}/.oh-my-zsh
      register: ohmyzsh_config

    - name: terminal | install ohmyzsh
      become: true
      become_user: "{{ user_name }}"
      shell: sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      when:  ohmyzsh_config.stat.exists == False and ansible_distribution != "Archlinux"

    - name: terminal | add aliases to bashrc
      blockinfile:
        path: /home/owen/.bashrc
        marker: "# {mark} ANSIBLE MANAGED BLOCK - terminal"
        block: "{{ terminal_aliases }}"

    - name: terminal | add aliases to zshrc
      blockinfile:
        path: /home/owen/.zshrc
        marker: "# {mark} ANSIBLE MANAGED BLOCK - terminal"
        block: "{{ terminal_aliases }}"

    - name: terminal | copy zsh powerline fonts
      copy:
        src: "fonts/ttf/MesloLGS NF"
        dest: "/home/{{ user_name }}/.local/share/fonts/ttf"
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        mode: "u=rw,go=r"
        backup: yes

    - name: terminal | set zsh as default user shell
      user:
        name: "{{ user_name }}"
        shell: /usr/bin/zsh

    - name: terminal | set zsh custom settings
      blockinfile:
        path: "/home/{{ user_name }}/.zshrc"
        marker: "# {mark} ANSIBLE MANAGED BLOCK - zsh"
        block: |
          setopt histignorespace
          setopt correct
          setopt extendedglob
          setopt nocaseglob
          setopt rcexpandparam
          setopt numericglobsort
          setopt nobeep
          setopt appendhistory
          setopt histignorelldups
          setopt autocd
          setopt inc_append_history

          zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'
          zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
          zstyle ':completion:*' rehash true

          zstyle ':completion:*' accept-exact '*(N)'
          zstyle ':completion:*' use-cache on
          zstyle ':completion:*' cache-path ~/.zsh/cache

          HISTFILE=~/.zhistory
          HISTSIZE=10000
          SAVEHIST=10000
