- name: terminal
  tags:
    - terminal
    - zsh
    - bash
  block:
    - name: terminal | install main termial applications
      package:
        name:
          - tmux
          - zsh

    - name: terminal | ohmyzsh
      become: true
      become_user: "{{ user_name }}"
      when: ansible_distribution != "Archlinux"
      block:
        - name: terminal | check for ohmyzsh
          stat:
            path: /home/{{ user_name }}/.oh-my-zsh
          register: ohmyzsh_config

        - name: terminal | install ohmyzsh
          shell: sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
          when:  ohmyzsh_config.stat.exists == False

        - name: terminal | clone zsh-syntax-highlighting
          ansible.builtin.git:
            repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
            dest: /home/{{ user_name }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting

        - name: terminal | clone zsh-syntax-highlighting
          ansible.builtin.git:
            repo: "https://github.com/zsh-users/zsh-history-substring-search"
            dest: /home/{{ user_name }}/.oh-my-zsh/custom/plugins/zsh-history-substring-search

        - name: terminal | clone zsh-autosuggestions
          ansible.builtin.git:
            repo: "https://github.com/zsh-users/zsh-autosuggestions"
            dest: /home/{{ user_name }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions

        - name: terminal | ohmyzsh plugins
          ansible.builtin.lineinfile:
            path: /home/{{ user_name }}/.zshrc
            regexp: '^plugins='
            line: plugins=(git zsh-syntax-highlighting zsh-history-substring-search zsh-autosuggestions)

        - name: terminal | ohmyzsh powerlevel10k
          block:
            - name: terminal | clone powerlevel10k
              ansible.builtin.git:
                repo: "https://github.com/romkatv/powerlevel10k.git"
                dest: /home/{{ user_name }}/.oh-my-zsh/custom/themes/powerlevel10k

            - name: terminal | ohmyzsh theme
              ansible.builtin.lineinfile:
                path: /home/{{ user_name }}/.zshrc
                regexp: '^ZSH_THEME='
                line: ZSH_THEME="powerlevel10k/powerlevel10k"

            - name: terminal | powerlevel10k config
              ansible.builtin.copy:
                src: "zsh/p10k.zsh" 
                dest: "/home/{{ user_name }}/.p10k.zsh"
                owner: "{{ user_name }}"
                group: "{{ user_name }}"
                mode: "u=rw,go=r"

    - name: terminal | add aliases to bashrc
      blockinfile:
        path: /home/owen/.bashrc
        marker: "# {mark} ANSIBLE MANAGED BLOCK - terminal"
        block: "{{ terminal_aliases }}"

    - name: terminal | add aliases to zshrc
      blockinfile:
        path: /home/owen/.zshrc
        marker: "# {mark} ANSIBLE MANAGED BLOCK - terminal"
        block: "{{ terminal_aliases }}"

    - name: terminal | copy zsh powerline fonts
      copy:
        src: "fonts/ttf/MesloLGS NF"
        dest: "/home/{{ user_name }}/.local/share/fonts/ttf"
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        mode: "u=rw,go=r"
        backup: yes

    - name: terminal | set zsh as default user shell
      user:
        name: "{{ user_name }}"
        shell: /usr/bin/zsh

    - name: terminal | set zsh custom settings
      blockinfile:
        path: "/home/{{ user_name }}/.zshrc"
        marker: "# {mark} ANSIBLE MANAGED BLOCK - zsh"
        block: |
          setopt histignorespace
          setopt correct
          setopt extendedglob
          setopt nocaseglob
          setopt rcexpandparam
          setopt numericglobsort
          setopt nobeep
          setopt appendhistory
          setopt histignorealldups
          setopt autocd
          setopt inc_append_history

          zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'
          zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
          zstyle ':completion:*' rehash true

          zstyle ':completion:*' accept-exact '*(N)'
          zstyle ':completion:*' use-cache on
          zstyle ':completion:*' cache-path ~/.zsh/cache

          HISTFILE=~/.zhistory
          HISTSIZE=10000
          SAVEHIST=10000
