- name: terminal
  tags:
    - terminal
    - zsh
    - bash
  block:
    - name: terminal | install main termial applications
      package:
        name:
          - tmux
          - zsh

    - name: terminal | add aliases to bashrc
      blockinfile:
        path: /home/owen/.bashrc
        marker: "# {mark} ANSIBLE MANAGED BLOCK - terminal"
        block: "{{ terminal_aliases }}"

    - name: terminal | add aliases to zshrc
      blockinfile:
        path: /home/owen/.zshrc
        marker: "# {mark} ANSIBLE MANAGED BLOCK - terminal"
        block: "{{ terminal_aliases }}"

    - name: terminal | copy zsh powerline fonts
      copy:
        src: "fonts/ttf/MesloLGS NF"
        dest: "/home/{{ user_name }}/.local/share/fonts/ttf"
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        mode: "u=rw,go=r"
        backup: yes

    - name: terminal | set zsh as default user shell
      user:
        name: "{{ user_name }}"
        shell: /usr/bin/zsh

    - name: terminal | set zsh custom settings
      blockinfile:
        path: "/home/{{ user_name }}/.zshrc"
        marker: "# {mark} ANSIBLE MANAGED BLOCK - zsh"
        block: |
          setopt histignorespace
          bindkey -v
