- name: ansible setup
  tags:
    - ansible
    - ansible-setup
  block:
    - name: ansible setup | ensure ansible is latest
      package:
        name: ansible
    
    - name: ansible setup | create log file
      file:
        path: /var/log/ansible.log
        owner: root
        group: root
        mode: 0664
        state: touch
      changed_when: False

