- name: aur setup
  tags:
    - aur
    - aur-setup
  block:
    - name: aur setup | create aur_builder user
      user:
        name: aur_builder
        create_home: yes
        group: wheel

    - name: aur setup | aur_builder sudo pacman access
      lineinfile:
        path: /etc/sudoers.d/11-install-aur_builder
        line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
        create: yes
        validate: 'visudo -cf %s'

    - name: aur setup | aur_builder temp directory
      file:
        path: /home/aur_builder/.ansible/tmp
        owner: "aur_builder"
        group: "wheel"
        state: directory

    - name: aur setup | aur_builder AccountsService File
      lineinfile:
        path: /var/lib/AccountsService/users/aur_builder
        line: '[User]'
        create: yes
    
    - name: aur setup | aur_builder System Account
      lineinfile:
        path: /var/lib/AccountsService/users/aur_builder
        line: 'SystemAccount=true'

