# Load distro-specific variables
- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- block:

  # Setup Ansible
  - import_tasks: ansible_setup.yml

  - import_tasks: software/package_managers.yml
  - import_tasks: software/terminal.yml
  - import_tasks: software/packages.yml
  - import_tasks: software/python.yml
