- name: i3
  tags:
    - i3
  block:
    - name: i3 | create config directory
      file:
        path: /home/{{ user_name}}/.i3
        owner: "{{user_name}}"
        group: "{{user_name}}"
        state: directory

    - name: i3 | copy config
      copy:
        src: i3/config
        dest: /home/{{ user_name }}/.i3/config
        owner: "{{user_name}}"
        group: "{{user_name}}"
        backup: yes
